### ISSUE TITLE
Pop-up sometimes isn't visible

### ISSUE THREAD

**Issue by Murderlon** [Skn0tt/alex-browser-extension#1]
<img width="779" alt="Screenshot 2019-06-30 at 21 22 02" src="https://user-images.githubusercontent.com/9060226/60401141-7e147d00-9b7d-11e9-9921-26b9e1cb3c3a.png">

Might be an `z-index` issue?

### Environment

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by Skn0tt** [comment]
Sorry for the late response. Fixed in 7c1b178942c462379bf7b1dddee091cda76649c6.
